name: ESLint and Prettier

on: [push]

jobs:
  vet:
    name: Run all code checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: |
          npm ci

      - name: Eslint
        run: |
          npm run lint-eslint

      - name: Prettier
        run: |
          npm run lint-prettier
